services:
  mariadb:
    image: mariadb:11.5.2
    container_name: chick
    environment:
      MARIADB_ROOT_PASSWORD: qwer1234
      MARIADB_DATABASE: chick
    ports:
      - "3308:3306"
    volumes:
      - ./db/:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf