spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/chick
    username: chick
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB




  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security:
    org.apache.kafka: OFF
    kafka: OFF
    org.springframework.kafka: OFF
    org.springframework.data.elasticsearch: DEBUG  # Elasticsearch ?? ??? ?? ???

#cloud:
#  aws:
#    credentials:
#      access-key: ${S3_ACCESS_KEY}
#      secret-key: ${S3_SECRET_KEY}
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
#    s3:
#      bucket: ${S3_BUCKET}


frontend:
  url:  https://bbiyagiez.netlify.app/

tag:
  version: 0.2.0
